version: "3.1"
volumes:
  mongo_data:
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      # These variables are passed to Dockerfile.
      args:
        - HOST_UID=${HOST_UID:-4000}
        - HOST_USER=${HOST_USER:-nodummy}
    restart: unless-stopped
    image: api:latest
    # links:
    #   - mongo
    ports:
      - 3002:3002
      - 9229:9229
    volumes:
      - ${PWD:-.}:/home/${HOST_USER}/${PROJECT_NAME}
      - /home/${HOST_USER}/${PROJECT_NAME}/node_modules

    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_DB_URL=${MONGO_DB_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - PORT=${PORT}
      - UID=${HOST_UID:-4000}
    command: ["yarn", "dev"]
    tty: true
    stdin_open: true
  # mongo:
  #   restart: unless-stopped
  #   image: mongo:3.6.4
  #   volumes:
  #     - mongo_data:/data/db
  #   ports:
  #     - 27017:27017
